project:
  type: book
  output-dir: docs

book:
  title: "MKTG5001 Labs"
  author: "Ahmad Daryanto"
  date: 2026-09-24
  date-format: "DD/MM/YYYY"
  chapters:
    - index.qmd
    - lab1.qmd
    - lab2.qmd
    - lab3.qmd
    - lab4.qmd
    - lab5.qmd
   

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual